### ISSUE TITLE
Asking for help about the trainning result?

### ISSUE THREAD

**Issue by dreamhua82** [LIAGM/LFattNet#7]

**Comment by LIAGM** [comment]
Hi,

Sorry about my 'fat' model.....
So I want to check you only want the training record about the LFattNet without attention module?
You want to compare the "validation MSE" and "badpixel rate" of different iterations?
Because our lab's machine broke several months ago, if you need these record I have to retrain my model.
You may need to wait about one week for the record, is it ok for your time?

Regards,

**Comment by dreamhua82** [comment]
Dear LIAGM, 
That's so kind of you. I need your training record (lf_LFattNet.txt )of both with attention module and without attention module. I want to see how it works, and compare my results.
Would you please send them to my email at your convenience?
Best wishes,
