### ISSUE TITLE
Questions about training

### ISSUE THREAD

**Issue by toughaaa** [LIAGM/LFattNet#9]
Dear LIAGM,
I have some questions about the training code：
1.  In the code, the epoch is set to 10000000. How long does each epoch takes, and how many epochs need to be trained in total?
2. I fit the environment as your describe, but an OOM error occurred. My GPU memory is 11G. Finally, I adjusted the number of 3D convolution kernels from 150 to 100 to run successfully.
Looking forward to your reply.
Thanks.

**Comment by LIAGM** [comment]
Hi,

1. Under the 1080TI GPU, each epoch may take about 4 hours and usually I will see whether the losses are converged or not, roughly it may take 30~40 epochs for training.
2. Due to the network architecture, the memory consumption is huge and if your GPU also have to display for the screen, the OOM error may occur under 11G GPU.

**Comment by toughaaa** [comment]
@LIAGM Thanks again for your reply.
